export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_ATTEMPT = 'FETCH_DATA_ATTEMPT';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const SAVE_STUDENT_ACTION = 'SAVE_STUDENT_ACTION';

export const SAVE_DATA_ATTEMPT = 'SAVE_DATA_ATTEMPT';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAIL = 'SAVE_DATA_FAIL';
export const RESET_SAVE_ACTION = 'RESET_SAVE_ACTION';